### ISSUE TITLE
Unable to access my account - syncing issues 

### ISSUE THREAD

**Issue by Quest4easy** [remnoteio/remnote-issues#228]
**Describe the bug**
I'm unable to log out from my chrome desktop browser. Remnote just displays a 'syncing'/'checking' message and I am still logged in to the platform. Any new Rems I create are not syncing to my android app or iPad. 

**To Reproduce**
1. Go to 'your name' in the sidebar
2. Click on 'your name/user account
3. Scroll down to 'logout....'
![image](https://user-images.githubusercontent.com/73546025/97327640-13587c00-186d-11eb-8a75-fe8c7ae7f52d.png)
![image](https://user-images.githubusercontent.com/73546025/97327661-18b5c680-186d-11eb-8b2e-d0717eb254f9.png)

**Expected behavior**
I expected to be logged out 

**Screenshots**
Above 

**Desktop (please complete the following information):**
 - OS: [e.g. windows]
 - Browser Chrome 
 - Version [not sure]

**Smartphone (please complete the following information):**

**Additional context**
I've sent an email via support.

**Comment by Quest4easy** [comment]
I've logged out by clearing my cache. When I log back in though I have the following page displayed (been like this for 15 minutes)
![image](https://user-images.githubusercontent.com/73546025/97333199-2e2def00-1873-11eb-8d57-ef2300924ed0.png)

**Comment by mfranzs** [comment]
Thanks for the report. Do you see any change if you refresh with Ctrl + Shift + R?

**Comment by Quest4easy** [comment]
Hi Martin,

First of all, great product.

Unfortunately, when I login via google authenticator (on my chrome
desktop), the following page is displayed. I can access my account via my
android app, but not on the desktop.
[image: image.png]
Ctrl + shift + R isn't doing anything for me.

Thanks

**Comment by Quest4easy** [comment]
If I login via Firefox or Edge on my desktop, I receive the following message
![image](https://user-images.githubusercontent.com/73546025/97341939-9386dd80-187d-11eb-97f0-2012a9e9ac25.png)

**Comment by Quest4easy** [comment]
Hi Martin,
I can access the platform now via my desktop Chrome browser.
Thanks

**Comment by Quest4easy** [comment]
Apologies, I spoke too soon. 
I am still having sync issues when I login. I've logged out in the hope the issue was fixed, but I'm in the previous loop. 
![image](https://user-images.githubusercontent.com/73546025/97354850-e9638180-188d-11eb-977c-85024b6655ff.png)

**Comment by Quest4easy** [comment]
> Thanks for the report. Do you see any change if you refresh with Ctrl + Shift + R?

@mfranzs, I'm having issues with the desktop logging into Remnote. 

1. Chrome - when I have successfully logged in this evening, no new entries are syncing to the cloud. When I logout, the system won't let me. I'm stuck between a rock and a hard place. (CTRL + SHIFT + R or manual refresh aren't working). 
2. Other browsers, I'm receiving the google authenticator issue as described above. 

In summary, I can't access my RemNote account to make any changes or edits. Any suggestions?

**Comment by mfranzs** [comment]
Sorry that you're still having problems. Could you please go to https://www.remnote.io/download_sync_debug_log and email us the downloaded debug log at support@remnote.io ? Thank you!

**Comment by Quest4easy** [comment]
Hi Martin,
I've removed the Remnote chrome extension from, uninstalled Chrome, amended
my proxy settings and it's now working. The issue didn't reside with
Remnote but was a problem with my chrome browser (potentially the
extension).
Anyway, it's now fixed and I can access my account on my desktop.

You can close this ticket.

Thanks

Darren

**Comment by mfranzs** [comment]
Great, thanks!
